### ISSUE TITLE
Modifications for building on ROS2 Humble

### ISSUE THREAD

**Issue by TitouanTyack** [kimsooyoung/mmwave_ti_ros#6]
Hi,

Thank you for sharing your work. I tried to use it on ROS2 Humble and I had some compiling issues. I fixed these by following these GitHub issues:
 - [for eloquent_composition.launch.py](https://github.com/Slamtec/sllidar_ros2/issues/2#issuecomment-1051023238)
 - [for mmWaveQuickConfig.cpp](https://cloud.tencent.com/developer/article/2027296)
 
 It seems to work with my AWR1843BOOST.
 
 Have you encountered these issues ? I can do a pull request if you want.
 
 Thanks again.
 Titouan

**Comment by kimsooyoung** [comment]
So much thank you for sharing your process. Honestly, I hadn't tried that with ROS 2 Humble.

If you can make PR, I'll try that on my system and will merge into main branch.

Have a great day and I'll wait for you PR ;)

**Comment by kimsooyoung** [comment]
PR Merged!
